export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

export const GET_GENRE_REQUEST = "GET_GENRE_REQUEST";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const GET_GENRE_FAIL = "GET_GENRE_FAIL";

export const GET_SIMILAR_REQUEST = "GET_SIMILAR_REQUEST";
export const GET_SIMILAR_SUCCESS = "GET_SIMILAR_SUCCESS";
export const GET_SIMILAR_FAIL = "GET_SIMILAR_FAIL";

export const GET_RECOMMENDATIONS_REQUEST = "GET_RECOMMENDATIONS_REQUEST";
export const GET_RECOMMENDATIONS_SUCCESS = "GET_RECOMMENDATIONS_SUCCESS";
export const GET_RECOMMENDATIONS_FAIL = "GET_RECOMMENDATIONS_FAIL";

export const GET_ERRORS = "GET_ERRORS";
